### ISSUE TITLE
Enhance feature cards styling

### ISSUE THREAD

**Issue by elie** [elie/simple-website#1]
The current feature cards could use some visual improvements to make them more engaging and modern. Here are some suggested enhancements:

### Proposed Changes
- Add icons at the top of each card to visually represent the feature
- Implement a more noticeable hover effect with smooth transitions
- Improve spacing and typography hierarchy
- Add a subtle gradient background to each card
- Include a soft border or accent color
- Enhance contrast between title and description

### Specific Style Updates
```css
.feature-card {
    /* Existing styles to keep */
    background: #fff;
    padding: 2rem;
    border-radius: 8px;
    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    transition: all 0.3s ease;
    
    /* New styles to add */
    border: 1px solid #e5e7eb;
    position: relative;
    overflow: hidden;
}

.feature-card::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 4px;
    background: linear-gradient(90deg, #6366f1, #8b5cf6);
    opacity: 0;
    transition: opacity 0.3s ease;
}

.feature-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 12px 24px rgba(0,0,0,0.1);
}

.feature-card:hover::before {
    opacity: 1;
}

.feature-card h3 {
    font-size: 1.5rem;
    margin: 1rem 0;
    color: #1f2937;
}

.feature-card p {
    color: #6b7280;
    line-height: 1.6;
}
```

### Icon Implementation
Consider adding FontAwesome or Material Icons for:
- "Easy to Use" card: A simple interface icon
- "Modern Design" card: A palette or layout icon
- "Fast & Reliable" card: A speedometer or checkmark icon

### Expected Outcome
These changes will make the feature cards more visually appealing while maintaining the clean and professional look of the website. The enhanced hover effects and visual hierarchy will improve user engagement.
